
CREATE TABLE CREDITCARD (
    CREDITCARD_NUMBER INT,
    ID INT,
    NAME VARCHAR(50),
    EXPIRATION DATE,
    SECURITY_CODE INT NOT NULL,
    PRIMARY KEY (CREDITCARD_NUMBER, ID)
);
INSERT INTO CREDITCARD
VALUES(1212, 5656, 'JACK','2023-06-01' ,123);