CREATE TABLE IF NOT EXISTS HEALTHIFO(
  ID INT,
  UPDATE_TIME DATE,
  HEIGHT DOUBLE,
  WEIGHT DOUBLE,
  BLOOD_PRESSURE DOUBLE,
  SLEEP_TIME DOUBLE,
  FOREIGN KEY (ID) REFERENCES `USER`(ID)
);

INSERT INTO HEALTHIFO
VALUES(6, '2023-06-15', 170, 65, 30, 8);
