CREATE TABLE QUESTION(
QUESTION_ID INT PRIMARY KEY,
ID INT,
QUESTION_MESSAGE VARCHAR(255));

INSERT INTO QUESTION
VALUES(123,1234,'hello');

SELECT * FROM QUESTION;

//VERSION2
CREATE TABLE QUESTION (
  QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
  ID INT,
  QUESTION_MESSAGE VARCHAR(255),
  CLINIC_DEPARTMENT_NAME VARCHAR(50),
  IS_ANSWERED BOOLEAN DEFAULT FALSE,
  IS_ACESSIBALE BOOLEAN DEFAULT FALSE
);


INSERT INTO QUESTION 
VALUES(2, 123, 'GOOD DAT', 'WAI', TRUE);
//auto-incrementを利用してquestion_idを省する
INSERT INTO QUESTION (ID, QUESTION_MESSAGE, CLINIC_DEPARTMENT_NAME)
VALUES (1234, 'hello', 'Some Department');

