DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT PRIMARY KEY,
   NAME VARCHAR(255));
INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World');
SELECT * FROM TEST ORDER BY ID;
UPDATE TEST SET NAME='Hi' WHERE ID=1;
DELETE FROM TEST WHERE ID=2;


INSERT INTO USER
VALUES(
	3,
	'ma',
	'pass'
	1,
	'2023-06-01',
	'phone',
	'email',
	'address'
	)
INSERT INTO `USER`(NAME,PSWD,GENDER,BIRTHDAY,TELEPHONE,MAILADDRESS,ADDRESS) VALUES('user','pass1',0,'2000-01-01','123456789','abc@gmail.com','11111');